"""Tests for the auto-generated-file guard module (plan 25)."""

from __future__ import annotations

import os
import time

import pytest

from kimi_cli.session import Session
from kimi_cli.tools.file.auto_generated import (
    CHECK_BYTE_COUNT,
    HEADER_LINE_LIMIT,
    _clear_marker_cache,
    assert_editable_file,
    assert_editable_file_content,
    build_auto_generated_error,
    detect_auto_generated_marker,
    extract_leading_header_comment_text,
    get_comment_styles_for_path,
    is_auto_generated_file_name,
    should_block_auto_generated,
    strip_bom,
)
from kosong.tooling import ToolError


@pytest.fixture(autouse=True)
def _fresh_cache():
    _clear_marker_cache()
    yield
    _clear_marker_cache()


# ═══════════════════════════════════════════════════════════════════════════
# Strong markers
# ═══════════════════════════════════════════════════════════════════════════


def test_marker_hash_generated():
    content = "# @generated\ncode here\n"
    assert detect_auto_generated_marker(content, "x.py") == "@generated"


def test_marker_go_protoc():
    content = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"
    marker = detect_auto_generated_marker(content, "x.go")
    assert marker is not None
    assert "protoc-gen-go" in marker


def test_marker_sql_automatically_generated():
    content = "-- This file was automatically generated\nSELECT 1;\n"
    marker = detect_auto_generated_marker(content, "q.sql")
    assert marker is not None


def test_marker_generated_by_sqlc():
    content = "// Generated by sqlc\npackage db\n"
    marker = detect_auto_generated_marker(content, "db.go")
    assert marker is not None
    assert "sqlc" in marker


def test_marker_html_comment():
    content = "<!-- @generated -->\n<html></html>\n"
    marker = detect_auto_generated_marker(content, "page.html")
    assert marker == "@generated"


def test_marker_case_insensitive():
    content = "// CODE GENERATED BY MOCKERY v2\npackage x\n"
    assert detect_auto_generated_marker(content, "x.go") is not None


def test_marker_block_comment():
    content = "/* @generated */\nint x;\n"
    assert detect_auto_generated_marker(content, "x.c") == "@generated"


def test_marker_multiline_block_comment():
    content = "/*\n * @generated\n */\nint x;\n"
    assert detect_auto_generated_marker(content, "x.c") == "@generated"


def test_marker_unknown_generator_not_matched():
    content = "// Generated by hand by the team\npackage x\n"
    assert detect_auto_generated_marker(content, "x.go") is None


# ═══════════════════════════════════════════════════════════════════════════
# False positives (strictness)
# ═══════════════════════════════════════════════════════════════════════════


def test_body_line_not_matched():
    """'code generated by' deep in the body (not header) must not match."""
    body = "\n".join(f"line {i}" for i in range(50)) + "\n# code generated by tool\n"
    assert detect_auto_generated_marker(body, "x.py") is None


def test_plain_auto_generated_comment_not_matched():
    content = "// auto-generated\npackage x\n"
    assert detect_auto_generated_marker(content, "x.go") is None


def test_generated_by_hand_not_matched():
    content = "# generated by hand\nprint(1)\n"
    assert detect_auto_generated_marker(content, "x.py") is None


def test_generated_in_prose_not_matched():
    content = "// This module handles generated report output.\npackage x\n"
    assert detect_auto_generated_marker(content, "x.go") is None


def test_no_header_at_all():
    content = "package x\n\nfunc main() {}\n"
    assert detect_auto_generated_marker(content, "x.go") is None


def test_marker_beyond_header_limit_not_matched():
    content = "\n".join(f"// filler {i}" for i in range(HEADER_LINE_LIMIT + 5))
    content += "\n// @generated\n"
    assert detect_auto_generated_marker(content, "x.go") is None


# ═══════════════════════════════════════════════════════════════════════════
# Filename patterns
# ═══════════════════════════════════════════════════════════════════════════


@pytest.mark.parametrize(
    "name",
    [
        "zz_generated.go",
        "foo.pb.go",
        "bar_pb2.py",
        "baz_pb2_grpc.py",
        "x.gen.ts",
        "generated.py",
        "api.swagger.json",
        "svc.openapi.json",
        "svc.mock.go",
        "svc.mocks.ts",
    ],
)
def test_generated_filenames(name):
    assert is_auto_generated_file_name(name)


@pytest.mark.parametrize(
    "name",
    ["main.go", "generated_report.go", "pb.go.bak", "mymocks_test.go", "gen.py"],
)
def test_regular_filenames(name):
    assert not is_auto_generated_file_name(name)


def test_filename_match_returns_name_as_marker():
    assert detect_auto_generated_marker("anything", "zz_generated.go") == "zz_generated.go"


# ═══════════════════════════════════════════════════════════════════════════
# Comment styles / header extraction
# ═══════════════════════════════════════════════════════════════════════════


def test_comment_styles_py():
    assert get_comment_styles_for_path("a.py") == ("hash",)


def test_comment_styles_ts():
    assert get_comment_styles_for_path("a.ts") == ("slash",)


def test_comment_styles_sql():
    assert get_comment_styles_for_path("a.sql") == ("sql",)


def test_comment_styles_html():
    assert get_comment_styles_for_path("a.html") == ("html",)


def test_comment_styles_dockerfile_makefile():
    assert get_comment_styles_for_path("Dockerfile") == ("hash",)
    assert get_comment_styles_for_path("Makefile") == ("hash",)
    assert get_comment_styles_for_path("Justfile") == ("hash",)


def test_extract_header_shebang_skip():
    content = "#!/usr/bin/env python3\n# @generated\nprint(1)\n"
    header = extract_leading_header_comment_text(content, ("hash",))
    assert "@generated" in header
    assert "python3" not in header


def test_extract_header_bom():
    content = "\ufeff# @generated\nprint(1)\n"
    header = extract_leading_header_comment_text(content, ("hash",))
    assert "@generated" in header


def test_extract_header_stops_at_code():
    content = "// header\n\ncode line\n// later comment\n"
    header = extract_leading_header_comment_text(content, ("slash",))
    assert "later comment" not in header
    assert "header" in header


def test_extract_header_blank_allowed_inside():
    content = "# part one\n\n# part two\nx = 1\n"
    header = extract_leading_header_comment_text(content, ("hash",))
    assert "part one" in header
    assert "part two" in header


def test_extract_header_no_comment():
    content = "code only\n"
    assert extract_leading_header_comment_text(content, ("hash",)) == ""


def test_strip_bom():
    assert strip_bom("\ufeffhi") == "hi"
    assert strip_bom("hi") == "hi"


def test_check_byte_count_limit_respected():
    # marker present only after CHECK_BYTE_COUNT chars → prefix is marker-free
    pad = "// " + "x" * CHECK_BYTE_COUNT
    content = pad + "\n// @generated\n"
    assert detect_auto_generated_marker(content, "x.go") is None


# ═══════════════════════════════════════════════════════════════════════════
# Setting gate + assert_* API (return ToolError | None — never raise)
# ═══════════════════════════════════════════════════════════════════════════


def test_should_block_defaults_true(session: Session):
    assert should_block_auto_generated(session) is True
    assert should_block_auto_generated(None) is True


def test_should_block_config_false(session: Session):
    session.custom_config = {"config_json": {"edit": {"block_auto_generated": False}}}
    assert should_block_auto_generated(session) is False


def test_assert_editable_file_content_refuses():
    err = assert_editable_file_content("# @generated\nx = 1\n", "x.py")
    assert isinstance(err, ToolError)
    assert "auto-generated" in err.message
    assert "x.py" in err.message


def test_assert_editable_file_content_filename():
    err = assert_editable_file_content("plain content\n", "zz_generated.go")
    assert isinstance(err, ToolError)


def test_assert_editable_file_content_passes_handwritten():
    assert assert_editable_file_content("# normal module\nx = 1\n", "x.py") is None


def test_assert_editable_file_content_setting_disabled(session: Session):
    session.custom_config = {"config_json": {"edit": {"block_auto_generated": False}}}
    assert (
        assert_editable_file_content("# @generated\nx = 1\n", "x.py", session=session)
        is None
    )


def test_build_error_message():
    err = build_auto_generated_error("path/x.py", "@generated")
    assert isinstance(err, ToolError)
    assert "Cannot modify auto-generated file" in err.message
    assert "@generated" in err.message
    assert "allow_auto_generated" in err.message


async def test_assert_editable_file_missing_ok(tmp_path):
    # new files are fine
    assert await assert_editable_file(str(tmp_path / "new.py")) is None


async def test_assert_editable_file_generated_refused(tmp_path):
    f = tmp_path / "svc.py"
    f.write_bytes(b"# @generated\ndata = 1\n")
    err = await assert_editable_file(str(f))
    assert isinstance(err, ToolError)
    assert "auto-generated" in err.message


async def test_assert_editable_file_handwritten_ok(tmp_path):
    f = tmp_path / "svc.py"
    f.write_bytes(b"# hand written\ndata = 1\n")
    assert await assert_editable_file(str(f)) is None


async def test_assert_editable_file_setting_disabled(tmp_path, session: Session):
    session.custom_config = {"config_json": {"edit": {"block_auto_generated": False}}}
    f = tmp_path / "svc.py"
    f.write_bytes(b"# @generated\ndata = 1\n")
    assert await assert_editable_file(str(f), session=session) is None


async def test_marker_cache_refreshed_on_rewrite(tmp_path):
    """Rewriting a generated file to hand-written content must re-scan."""
    f = tmp_path / "mod.py"
    f.write_bytes(b"# @generated\ndata = 1\n")
    assert await assert_editable_file(str(f)) is not None

    # rewrite as hand-written; bump mtime so the (mtime_ns, size) key changes
    f.write_bytes(b"# totally hand written now\ndata = 2\n")
    future = time.time() + 5
    os.utime(f, (future, future))
    assert await assert_editable_file(str(f)) is None


async def test_marker_cache_serves_same_stat(tmp_path):
    f = tmp_path / "mod.py"
    f.write_bytes(b"# @generated\ndata = 1\n")
    assert await assert_editable_file(str(f)) is not None
    # second call hits the cache and still refuses
    assert await assert_editable_file(str(f)) is not None


async def test_generated_filename_refused_regardless_of_content(tmp_path):
    f = tmp_path / "zz_generated.deepcopy.go"
    f.write_bytes(b"package x\n")
    err = await assert_editable_file(str(f))
    assert isinstance(err, ToolError)
    assert "zz_generated.deepcopy.go" in err.message
